version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local